<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lab 2</title>
	<style>
		span {
			display: inline-block;
			font-weight: bold;
			margin-bottom: 5px;
		}
		form {
			margin-bottom: 20px;
		}
		.no-display {
			display: none;
		}
		.cached {
			font-style: italic;
			font-weight: normal;
			margin: 0 5px;
		}
	</style>
</head>

<body>
	<?php
		isConnectionSet($client, $db, $collection);
	?>